### ISSUE TITLE
supplement figs 5-7 with over-plotted Abias=0 posteriors

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#10]
Suggestion: In figs 5, 6 and 7 I suggest you include, in the panels that show the 1D-posterior distributions
for the individual parameters, the corresponding distributions obtained from the chains with A_cen=A_sat=0.
That way you can immediately see by what amount the posterior distributions are broadened due to
the added freedom…

**Comment by andrew-zentner** [comment]
I will try to figure out how to do this. It may be slightly non-trivial because I make these plots using the "corner" plotting package that comes with emcee. I will look into this.

**Comment by aphearin** [comment]
This suggestion was made by @vdbosch69 by email, copied here for the convenience of @andrew-zentner by me. 

Here is what I suggest instead. Make an entirely separate figure comparing the 1d posteriors obtained for models with and without assembly bias. The downside is that this would be slightly redundant with the corner plot. However, I think that downside is outweighed by the advantages:
1. To modify the corner plot, you'd need to customize corner.py, which will be nontrivial. Making a separate figure has the distinct advantage of being easy to do.
2. The modified corner plot would in my opinion be too busy. This is an aesthetic judgement call, obviously, but I have a fairly strong opinion that the modified plot would contain too many points to absorb by almost all our readers. The modified plot would contain multiple different kinds of information, which is almost always a sign that a separate figure is warranted for the sake of the reader. Dense plots are rarely appreciated. A separate, standalone plot calls direct attention to a qualitatively new point that is worthy of contemplation in its own right.

**Comment by vdbosch69** [comment]
Agreed.

**Comment by andrew-zentner** [comment]
I really like this idea.

**Comment by andrew-zentner** [comment]
Done. I compromised by adding these posteriors to the diagonal panels in the triangle plots that show the 1D posteriors. I think this compromise is adequate. Putting multiple contours on the same plots is too busy.
