### ISSUE TITLE
figure showing direct HODs

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#11]
I think it would be very useful/powerful to also show actual HODs
( <N>  vs.  M  for    (i) old Zehavi model (ii) Zentner+16 model w/o assembly bias
and (iii) Zentner+16 model WITH assembly bias.
And perhaps we can say a few words about satellite fractions, or something like that…

**Comment by aphearin** [comment]
Ok @vdbosch69 and @andrew-zentner, so here is a crude plot I made. I'll be prettying this up over the next day or so, but I thought I'd share the basic result straight away. 

I made these simply by randomly selected parameter sets chosen from the MCMC chains such that \chi^2 - \chi^2_min < 1, repeatedly populating mocks from those parameters, and then manually tabulating the HODs. In the "assembly-biased model", A_bias has been allowed to float in the chains, whereas in the "standard model", that's just Zheng+07. These plots pertain to a -20 threshold.

UPDATE: The plots below are corrected from their original posting. The originally posted plots had a bug, these are correct. 

![output_4_0](https://cloud.githubusercontent.com/assets/6951595/15895441/54eef90e-2d59-11e6-8be9-d6dbecc54ddd.png)
![output_5_0](https://cloud.githubusercontent.com/assets/6951595/15895443/56e6f162-2d59-11e6-8715-31e3a9b398e9.png)

**Comment by aphearin** [comment]
@vdbosch69 and @andrew-zentner now that we have results done for this new plot, please let me know what comments you may have for making these figures look cosmetically appealing. I think they look pretty good as is, so I'll wait to hear from you until I work on this further.

**Comment by vdbosch69** [comment]
This looks more believable.....and aliong the lines that we might expect.  I think it would be nice if we could plot actual 69 and/or 95 percent confidence intervals as obtained from the posteriors....That way the significance is immediately apparent.  For Zehavi+11 we can simply show the result as is....

**Comment by andrew-zentner** [comment]
Probably the clearest way to make the plot is as follows. No need to populate mocks. Just use the analytic HOD expressions. Then sample, say 50, random models within some distance of the best-fit model. This will lead to a set of curves. The correspondence between Delta Chi^2 and the confidence level will not be exact because the posteriors are not Gaussian, but it should give a rough idea of the uncertainty.

**Comment by vdbosch69** [comment]
I agree that you should use analytical HOD expressions, but don't see why you need to cut corners.
It is trivial to read in the entire chain (or a subsample of say 10^4 elements). For each M, you then compute <N|M> for each chain element.
You rank order the results, and you pick the elements that bracket the 68 percentile range. Two simple loops (one over the mass bins, one over all chain elements) ....actual computation is negligible...

**Comment by vdbosch69** [comment]
Something went wrong...what I wanted to say is that you compute N for that M  for each chain element from the analytical HOD model....then rank order....etc

**Comment by andrew-zentner** [comment]
Yes, that is also easy to do. In that case, it is easy to use all 10^6 elements. But two things can go awry there. First, your result depends upon the binning. Maybe not such a big deal, just use a huge number of bins. Second, though, you lose the sense of the correlation of viable HODs as a function of mass. Showing samples preserves this so long as some of the lines are visible independently of one another. That is why I prefer the sampling option. However, I am willing to go with either option.

**Comment by vdbosch69** [comment]
agreed....as for the number of bins, not a big deal indeed. Using bins of 0.1 in log M should be MORE than adequate

**Comment by aphearin** [comment]
@andrew-zentner and @vdbosch69 - it's easier to calculate the marginalized HOD in the assembly bias model by populating mocks and manually tabulating. I think it would be tedious to analytically calculate the marginalized HOD for the assembly-biased models. For the standard model, what you recommend doing is straightforward. 

Shown below is a figure update showing error bands. All I did was generate 100 mocks, and calculate the variance of <Ncen> and <Nsat> in each mass bin. That's all that's plotted. 

![output_4_0](https://cloud.githubusercontent.com/assets/6951595/15898010/99b6528e-2d64-11e6-8e0d-422843798fed.png)
![output_6_0](https://cloud.githubusercontent.com/assets/6951595/15898013/9c6a030e-2d64-11e6-8c35-9b6e67b27211.png)

**Comment by vdbosch69** [comment]
I like

**Comment by andrew-zentner** [comment]
it's easier to calculate the marginalized HOD in the assembly bias by populating mocks and manually tabulating ....

I don't see why it would be easier. Our model fixes the marginalized HOD to be given by the 5 standard HOD parameters. So you can use the 5-parameter model to get it.

I like the plot though. I just hate the color scheme. That blue and red hurts my brain ;-).

**Comment by aphearin** [comment]
Right, sure, but I'm not sure I propagated the _baseline_ behavior of the component occupation model up to the composite. Let me check.

**Comment by aphearin** [comment]
Here's an updated figure with different color scheme. The advantage of doing the calculation the way I have done it is that it is now done. Unless you see a flaw in this method, I'd rather just work on figure cosmetics and not rewrite the analysis method. 

![output_4_0](https://cloud.githubusercontent.com/assets/6951595/15898667/2da9cece-2d67-11e6-90ed-f68d811d9a1b.png)
![output_6_0](https://cloud.githubusercontent.com/assets/6951595/15898671/2f22c0ee-2d67-11e6-80c7-cc31c2581d90.png)

**Comment by andrew-zentner** [comment]
OK. Fine with me. I just was doing it the other way.

**Comment by aphearin** [comment]
The only reason there should be a difference is if there is a bug in halotools monte carlo routines. I'll update the paper and include this figure momentarily, closing this issue when I do. Feel free to chime in with cosmetic comments.
