### ISSUE TITLE
Proposal to omit Discussion section entirely

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#12]
@andrew-zentner and @vdbosch69 - I have a bold proposal. Let's not even have a discussion section. The results are so straightforward that I don't see a lot of room for jazz. Plus, as @vdbosch69 and I discussed yesterday, the Intro and Discussion in my last paper are extremely thorough (and so long!), that much of what we'd discuss would be redundant.

**Comment by vdbosch69** [comment]
We don't need a thorough discussion section, but we need a summary section, briefly summarizing our results. We can weave any `discussion' (i.e., implications of our results) into that summary section.

**Comment by aphearin** [comment]
Agreed on all counts. Current version of master has a bullet-point summary that I figured we could add to for this purpose.

**Comment by andrew-zentner** [comment]
So, I just went through the paper. I think that adding a final paragraph to our conclusion section should suffice. I agree that our results are simple and don't need to be discussed ad nauseum in a discussion section. I just need to think of what to add in this section.

**Comment by aphearin** [comment]
Ok, great. I'll go ahead and close this then, since there is no danger that you'll forget to add more text to the conclusions section.
