### ISSUE TITLE
Include data storing the chains as part of the publication

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#13]
I think it is a good idea to make the likelihood chains publicly available. This can be in the simple form of an astropy table that @andrew-zentner has recently provided me. Just like we did with the Decorated HOD paper, how that paper was accompanied by an IPython Notebook that people could use to reproduce our results, I think we should include chains that people can directly sample themselves. This not only makes our results more transparent and reproducible, but just as importantly this can directly promote other research that immediately builds on what we've done. For example, by sampling our chains, we make it easy for people to study what additional constraining power comes from additional statistics. 

What do you think @andrew-zentner and @vdbosch69?

**Comment by andrew-zentner** [comment]
I will host this on my own web site. However, if it doesn't offend @aphearin, I may like to submit before I have this all sorted out.

**Comment by aphearin** [comment]
Ha! No, no "offense" taken. This is probably lagniappe anyway.
