### ISSUE TITLE
compiling the latex file

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#19]
There is now an executable script that repeatedly compiles the latex document to make sure all references appear in the pdf. Just type ./compile_script.sh. Note that this script also automatically fixes offensive British spellings that may have crept into the paper. 

@vdbosch69 @andrew-zentner

**Comment by vdbosch69** [comment]
script is not working. You need to change
bibtex ms.bib
to 
bibtex ms

**Comment by aphearin** [comment]
My bad. I won't be able to fix this until Monday.

**Comment by aphearin** [comment]
This should now be fixed.
