### ISSUE TITLE
Comments from Frank

### ISSUE THREAD

**Issue by vdbosch69** [andrew-zentner/abmcmc#25]
Section 2.1.2.  I think we need to point out to the reader that our model is subtly different from that of Zehavi et al.  (in terms of us not multiplying <Nsat> with <Ncen>). We can simply mention why we do not include that term, and point out that this does not in any way cause a significant change of the results.
In my opinion we CANNOT say that we mimic the standard HOD of Zehavi et al. without mentioning this difference.

Section 2.1.4. I think we should give a bit more detail as to the computation of w_p, beyond `as described in detail in http://halotools.readthedocs.io'.  I am a strong oponent of papers having to be self-containing as much as possible. I suggest we say a few words about how we construct the randoms.

For the same reason, I think the paper should also be a bit more explicit regarding the Decorated HOD model. I have included now, in section 2.2, an equation that makes it explicit how Acen and Asat modify the HOD (this is only valid for f_split =0.5, as I indicate). PLEASE CHECK TO MAKE SURE THAT THIS EQUATION IS CORRECT.

I have added a summation sign to the first term in Eq. 4. If you don't like it, than please point out that we use Einstein summation convention....

In Section 3.1, first paragraph, you write that the 50 randomly selected models in Figs 2-4 are selected from the MCMC chains within Delta Chi2 < 1. However, in the caption of Fig 2 you write that you use Delta Chi2 < 5.89....This needs to be corrected. Also, when quoting such specific numbers, make sure 
that they are consistent with a statement in captions of Figs 3 and 4 that state `same as fig 2....'

Caption of Table 3.2 and Section 3.2, third paragraph. I do NOT understand what you mean by
..`where the posterior on a parameter is monotonic within the physical parameter space'....Could you please rephrase this...

Finally, I have corrected a few typos in the text.

**Comment by andrew-zentner** [comment]
Frank, did you commit this yet? I don't see it.

Also, I have addressed many of these already. I will comment and close this issue asap.

**Comment by vdbosch69** [comment]
I have trouble committing
Github is not doing what I think it should be doing.
HELP IS NEEDED

# 

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by aphearin** [comment]
@vdbosch69 - I think the version of `master` that @andrew-zentner committed in https://github.com/andrew-zentner/abmcmc/commit/6f630de82aaa763b8c1706656cd756ee9b1f2897 addresses your first point, doesn't it? Are you sure you were looking at an up-to-date version of `master`?

As for your second comment: I disagree and I do not think it is necessary to describe how RR is computed. There are _lots_ of details we are leaving out, for example what is our numerical method for evaluating the `erf` function. The only truly "self-contained" paper would be infinite in length. What gets included is a subjective judgement call. This particular detail strikes me as totally overkill. The only reader who would be interested in this fine-grained detail would be a reader who is trying to exactly reproduce our results. Such a reader would need to read the code anyway, so including it here seems redundant and not worth the space.

I have the exact same opinion about your comment about A_cen and A_sat. Anyone who cares about this implementation detail will need to read Hearin+16 anyway, so what is the point?

**Comment by andrew-zentner** [comment]
As far as wp(rp), I actually use CorrFunc, so I rewrote that entire section.

**Comment by vdbosch69** [comment]
When I started editting the file was up to date. When I tried to committ it was behind. Now it won;t let me commit. Will send the tex file to AZ.

As for AH comments; I strongly disagree. I just added one equation that shows how Acen and Asat enter. There are MANY people interested in this stufff who have NOT read Hearin+16, and if we can expain to them what the model does without them having to read it, it is worth 1-2 sentences. As for the RR I don't have strong feelings, but I think mentioning in a few words how the randoms were selected is not redundant at all. It is NOT the same as explaining how erf is computed.

**Comment by aphearin** [comment]
Ok @vdbosch69. I think we just disagree, but I also don't think this is worth arguing about, so if you already took the time to implement the change then I'm certainly fine with having this appear in the draft.

**Comment by andrew-zentner** [comment]
I think this statement is all that is needed for the wp calculation. I am certainly not going to summarize CorrFunc. Note that the information that was previously there was not correct. CorrFunc counts pairs and uses the analytic expression for random probabilities, which is entirely appropriate for a simulation analysis.

Having populated mocks, we perform the computation of the projected two-point galaxy correlation 
function, $w_{\rm p}(r_{\rm p})$ using the publicly-available {\tt CorrFunc} package \citep{corrfunc} which has been extensively optimized for computational speed.

**Comment by vdbosch69** [comment]
I created a pull request. Could you please check to see whether you can 
merge this. Am still experiencing all sorts of shit here with git, so I just want to
be sure you got the changes I made…

F

# 

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by andrew-zentner** [comment]
All fixed.
