### ISSUE TITLE
monotonic statement is still unclear to me

### ISSUE THREAD

**Issue by vdbosch69** [andrew-zentner/abmcmc#31]
In caption of Table 2, and somewhere in the text, you write

In cases for which the posterior is monotonic within the physical parameter
space, we show one-sided percentiles.

I do NOT understand what you mean by the posterior being monotonic within the physical parameter space.....

**Comment by andrew-zentner** [comment]
Purely increasing or decreasing. It doesn't have a turnover, so it doesn't really make much sense to have two-sided constraints.

**Comment by vdbosch69** [comment]
with what???? I _do_ know what monotomic means…
You are talking about a 1D distribution….so monotonic in what sense?????

# 

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by andrew-zentner** [comment]
OK, let's back up.
1. I'm talking about the 1D posterior so that is a function of a single variable, agreed?
2. The variable is the value of the parameter of interest, say Acen, agreed?
3. Most posteriors are not monotonic within the physical parameter space, they have a peak and we define a parameter confidence region based on the shape of the posterior function. Agreed?
4. If a posterior is monotonic, then there is no obvious sense in a 2-sided confidence region. The posterior will peak at one or the other end of the viable region of parameter space. Agreed?
5. If a posterior is a monotonic function, then it is more informative to quote the 1-sided confidence region. Agreed?
Let me know where this breaks down. I honestly don't know a better way to say it.

**Comment by vdbosch69** [comment]
OK. I now understand what you are trying to say, and I agree with that.

I do not think, though, that  your way of saying it is clear. I will think of
alternative ways of formulating this. If unsuccesful, I will leave as is.

An working on Section 4 now…

F

# 

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by andrew-zentner** [comment]
yes, please do.

Andrew R. Zentner
Associate Professor
Director of Graduate Studies
Department of Physics and Astronomy &
Pittsburgh Particle physics, Astrophysics and Cosmology Center (PITT PACC)
University of Pittsburgh
320 Allen Hall
Pittsburgh, PA 15260

zentner@pitt.edumailto:zentner@pitt.edu
http://www.phyast.pitt.edu/~zentner/Home.html

On Jun 17, 2016, at 2:34 PM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:

OK. I now understand what you are trying to say, and I agree with that.

I do not think, though, that your way of saying it is clear. I will think of
alternative ways of formulating this. If unsuccesful, I will leave as is.

An working on Section 4 now…

F

# 

Prof. Frank C. van den Bosch e-mail: frank.vandenbosch@yale.edumailto:frank.vandenbosch@yale.edu
Astronomy Department, Yale University phone: +1-203-432-0196
P.O. Box 208101 fax: +1-203-432-5048

# New Haven, CT 06520-8101 http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by vdbosch69** [comment]
How about this change:

In cases where the posterior distribution of either $A_{\rm cen}$ or $A_{\rm sat}$ is
a monotonic within the physical parameter range, we quote an upper or lower limit on the parameter

to

In cases where the posterior distribution of either $A_{\rm cen}$ or $A_{\rm sat}$ peaks
at the physical boundaries ($\pm 1)$,  we only quote an upper or lower limit on the parameter

# F

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch

**Comment by vdbosch69** [comment]
Ignore my previous suggestion...rather I suggest the following:

In cases where the 16 or 84 percentiles coincide with a physical or prior bound, we only quote a lower or upper limit on the parameter, respectively.

**Comment by andrew-zentner** [comment]
That can never happen, by definition, so that rewrite doesn't work.

Andrew R. Zentner
Associate Professor &
Director of Graduate Studies
Department of Physics & Astronomy
The University of Pittsburgh

On Jun 17, 2016, at 4:49 PM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:

Ignore my previous suggestion...rather I suggest the following:

In cases where the 16 or 84 percentiles coincide with a physical or prior bound, we only quote a lower or upper limit on the parameter, respectively.

##

**Comment by vdbosch69** [comment]
> That can never happen, by definition, so that rewrite doesn't work.

Yes it can. Consider a posterior distribution, say for A_{cen}, which peaks at 0.95 or so.  
Suppose the value of the posterior probability at this peak is Pmax. 

For each value of A_{cen}  there is a corresponding value of the posterior probability, P.

In order to  determine the 16 and 84 percentiles, what do you do? Well, you find the posterior
probability P_{68}  such that 68 percent of the chain elements have P>P_{68}.
In the example, you see that the values of A_{cen}  that correspond to this P_{68} are
A_{16} (the 16 percentile) and the prior constraint +1.  I hope the example demonstrates
that 84 percentiles can coincide with the upper limit…..

Frank

> Andrew R. Zentner
> Associate Professor &
> Director of Graduate Studies
> Department of Physics & Astronomy
> The University of Pittsburgh
>

**Comment by andrew-zentner** [comment]
What you describe is not a percentile. It is a probability threshold.

Andrew R. Zentner
Associate Professor &
Director of Graduate Studies
Department of Physics & Astronomy
The University of Pittsburgh

On Jun 18, 2016, at 4:02 PM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:

> That can never happen, by definition, so that rewrite doesn't work.

Yes it can. Consider a posterior distribution, say for A_{cen}, which peaks at 0.95 or so.
Suppose the value of the posterior probability at this peak is Pmax.

For each value of A_{cen} there is a corresponding value of the posterior probability, P.

In order to determine the 16 and 84 percentiles, what do you do? Well, you find the posterior
probability P_{68} such that 68 percent of the chain elements have P>P_{68}.
In the example, you see that the values of A_{cen} that correspond to this P_{68} are
A_{16} (the 16 percentile) and the prior constraint +1. I hope the example demonstrates
that 84 percentiles can coincide with the upper limit.....

Frank

> Andrew R. Zentner
> Associate Professor &
> Director of Graduate Studies
> Department of Physics & Astronomy
> The University of Pittsburgh
> 
> On Jun 17, 2016, at 4:49 PM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>mailto:notifications@github.com> wrote:
> 
> Ignore my previous suggestion...rather I suggest the following:
> 
> In cases where the 16 or 84 percentiles coincide with a physical or prior bound, we only quote a lower or upper limit on the parameter, respectively.
> 
> ## 
> 
> You are receiving this because you commented.
> 
> ## Reply to this email directly, view it on GitHubhttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fandrew-zentner%2fabmcmc%2fissues%2f31%23issuecomment-226878012&data=01%7c01%7czentner%40pitt.edu%7c3a061b3b43f841c8abed08d396f0e3a0%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=B6a5C9Dmi0F2xTorJmnRNrAmyraRXwEdBd%2forg5Mhq8%3d, or mute the threadhttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2fAIhmmw9eqElzB9BxyNgnGv8KKSk39-sqks5qMwhcgaJpZM4I4mdo&data=01%7c01%7czentner%40pitt.edu%7c3a061b3b43f841c8abed08d396f0e3a0%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=vb9k%2fcmzerlpK1IKQmlmuWPRPU6PHPaPXh%2fq%2fbY5Jqw%3d.
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

##

**Comment by vdbosch69** [comment]
> What you describe is not a percentile. It is a probability threshold.

Fair enough….I guess what I was describing is the 68 % Confidence interval.
So then perhaps what you can say is

In cases where the upper or lower bound of the 68 percent confidence interval 
coincides with a physical or prior bound, we only quote a lower or upper limit 
on the parameter, respectively.

Sorry to go on about this, but I find that statement about the monotonicity 
incomprehensible…

F

> Andrew R. Zentner
> Associate Professor &
> Director of Graduate Studies
> Department of Physics & Astronomy
> The University of Pittsburgh
>

**Comment by andrew-zentner** [comment]
The reason I don't like saying that is that there is no unambiguous meaning to the phrase "68% confidence interval." There are many possible choices for such an interval and different authors make different choices. The only requirement is that the interval contain 68% of the posterior. To me, the statement that the posterior PDF increases monotonically toward a physical boundary of the parameter space is completely unambiguous.

**Comment by vdbosch69** [comment]
The reason I don't like saying that is that there is no unambiguous meaning to the phrase "68% confidence interval." There are many possible choices for such an interval and different authors make different choices. The only requirement is that the interval contain 68% of the posterior. To me, the statement that the posterior PDF increases monotonically toward a physical boundary of the parameter space is completely unambiguous.

Well, it is your call. The posterior is on A_{sat} for the -19 sample (Fig 5) is NOT monotonic, yet, you
quote only a lower bound in Table 2. But if you want to stick with your description, that is fine with me.

\

**Comment by andrew-zentner** [comment]
I'll think it over.

Andrew R. Zentner
Associate Professor &
Director of Graduate Studies
Department of Physics & Astronomy
The University of Pittsburgh

On Jun 20, 2016, at 9:02 AM, Frank C. van den Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:

The reason I don't like saying that is that there is no unambiguous meaning to the phrase "68% confidence interval." There are many possible choices for such an interval and different authors make different choices. The only requirement is that the interval contain 68% of the posterior. To me, the statement that the posterior PDF increases monotonically toward a physical boundary of the parameter space is completely unambiguous.

Well, it is your call. The posterior is on A_{sat} for the -19 sample (Fig 5) is NOT monotonic, yet, you
quote only a lower bound in Table 2. But if you want to stick with your description, that is fine with me.

\

> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_andrew-2Dzentner_abmcmc_issues_31-23issuecomment-2D227122993&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=akBy6VKVSXuVF7qPhX_uKgCTzeIo3SdhrMQi2H7IAuI&m=oP5blV3vjUG5RtOaS2bnBbytaSdKI2IqXEUVyxJRQEc&s=eceJx28jvXC-T4xvy0VVi0OzZisRsmtmj27W5rCwFD4&e=, or mute the thread https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe_AIWS8QRnIpO-5Fj8itJp1YUDf7PbYn9AVXks5qNoC5gaJpZM4I4mdo&d=CwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=akBy6VKVSXuVF7qPhX_uKgCTzeIo3SdhrMQi2H7IAuI&m=oP5blV3vjUG5RtOaS2bnBbytaSdKI2IqXEUVyxJRQEc&s=XtnzKzhFC-w9TwLWTqU8w8kV26nxqWE5l2Vr0ifMHyk&e=.

##

**Comment by andrew-zentner** [comment]
Tried one more phrasing. Check it out.

**Comment by vdbosch69** [comment]
YES. Much better. I like it. Please also rewrite this in the caption of Table 2!

Thanks!!!!

# 

Prof. Frank C. van den Bosch                        e-mail: frank.vandenbosch@yale.edu
Astronomy Department, Yale University                            phone: +1-203-432-0196
P.O. Box 208101                                                                     fax: +1-203-432-5048

# New Haven, CT 06520-8101                              http://www.astro.yale http://www.astro.yale/.edu/vdbosch
