### ISSUE TITLE
assembly bias explanation

### ISSUE THREAD

**Issue by vdbosch69** [andrew-zentner/abmcmc#32]

**Comment by vdbosch69** [comment]
I am a bit confused by AZ's statement that

Moreover, high concentrations due to tidal
truncation are a hallmark of splashback halos
\citep{wang_etal07,dalal_etal08,sunayama_etal16}.

First of all,I think the reference to wang_etal07 must be wang_etal09.
Secondly, I would expect splashback halos to have LOWER concentrations (a natural outcome of stripping the outer layers).....

**Comment by aphearin** [comment]
I think this now resolved after a Slack discussion. Reopen if not.
