### ISSUE TITLE
Calculating wp

### ISSUE THREAD

**Issue by aphearin** [andrew-zentner/abmcmc#7]
An important section that is missing is the one describing how we compute w_p(r_p).
Once we have populated the simulation box, how exactly do we compute the projected
correlation function. What are the integration limits (for the projection integral), etc.

**Comment by aphearin** [comment]
@andrew-zentner, this is my attempt to resolve one of the issues brought up in Frank's email. You can see how I have tried to address this in the following commit: https://github.com/andrew-zentner/abmcmc/commit/7150329c2a026cd5afbd0f2fc7826ecb7d5f1faa. Please be absolutely sure that I have correctly described your choice for pi_max. You should also add what the rp_bins are.

**Comment by andrew-zentner** [comment]
Made some small changes, but this should be good to go now.
